version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @ionic/cli
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build:prod
artifacts:
  files:
    - '**/*'
  base-directory: www
