version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
      - apt install -y openjdk-11-jdk
      - sudo apt -y install android-sdk
      - echo 'export ANDROID_SDK_ROOT=/usr/lib/android-sdk' >> ~/.bashrc
      - echo 'export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools' >> ~/.bashrc
      - . ~/.bashrc
      - apt -y install sdkmanager
      - sdkmanager "platforms;android-30" "build-tools;30.0.3"
      - echo "y" | sdkmanager --licenses
      - npm install -g @ionic/cli@latest
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build:prod
      - npm install -g cordova 
      - ionic cordova platform add android 
      - npm i -g cordova-res
      - ng add @ionic/cordova-builders
      - ionic cordova build android --release
      - aws s3 cp platforms/android/app/build/outputs/apk/release/* s3://ionic-app-umair
artifacts:
  files:
    - '**/*'
  base-directory: www
